# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 245)
        Dialog.setMinimumSize(QtCore.QSize(350, 245))
        Dialog.setMaximumSize(QtCore.QSize(350, 247))
        Dialog.setWindowTitle("联系作者")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/photo/img/header.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.authorQr = QtWidgets.QLabel(Dialog)
        self.authorQr.setMaximumSize(QtCore.QSize(150, 150))
        self.authorQr.setText("")
        self.authorQr.setPixmap(QtGui.QPixmap(":/photo/img/lx.jpg"))
        self.authorQr.setScaledContents(False)
        self.authorQr.setAlignment(QtCore.Qt.AlignCenter)
        self.authorQr.setObjectName("authorQr")
        self.horizontalLayout.addWidget(self.authorQr)
        self.money = QtWidgets.QLabel(Dialog)
        self.money.setMaximumSize(QtCore.QSize(150, 150))
        self.money.setText("")
        self.money.setPixmap(QtGui.QPixmap(":/photo/img/sk.jpg"))
        self.money.setScaledContents(False)
        self.money.setAlignment(QtCore.Qt.AlignCenter)
        self.money.setObjectName("money")
        self.horizontalLayout.addWidget(self.money)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.info.setFont(font)
        self.info.setTextFormat(QtCore.Qt.AutoText)
        self.info.setAlignment(QtCore.Qt.AlignCenter)
        self.info.setObjectName("info")
        self.verticalLayout_3.addWidget(self.info)
        self.ok = QtWidgets.QDialogButtonBox(Dialog)
        self.ok.setOrientation(QtCore.Qt.Horizontal)
        self.ok.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.ok.setCenterButtons(False)
        self.ok.setObjectName("ok")
        self.verticalLayout_3.addWidget(self.ok)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.ok.accepted.connect(Dialog.accept)
        self.ok.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setToolTip(_translate("Dialog", "联系作者,"))
        self.label_3.setText(_translate("Dialog", "添加好友"))
        self.label_2.setText(_translate("Dialog", "打赏作者"))
        self.info.setText(_translate("Dialog", "算卦以及软件问题请微信扫码联系作者"))
import images_rc
