# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(728, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(728, 350))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/512.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 30))
        self.label_2.setMaximumSize(QtCore.QSize(40, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(60, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(60, 30))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(40, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(40, 30))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(30, 30))
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(41, 30))
        self.comboBox_3.setMaximumSize(QtCore.QSize(41, 30))
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMinimumSize(QtCore.QSize(40, 30))
        self.comboBox_4.setMaximumSize(QtCore.QSize(40, 30))
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMinimumSize(QtCore.QSize(41, 30))
        self.comboBox_5.setMaximumSize(QtCore.QSize(41, 30))
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_5)
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(30, 30))
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 30))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 30))
        self.label_10.setMaximumSize(QtCore.QSize(40, 30))
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(60, 30))
        self.comboBox_6.setMaximumSize(QtCore.QSize(41, 30))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(30, 30))
        self.label_7.setMaximumSize(QtCore.QSize(30, 30))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setMinimumSize(QtCore.QSize(41, 30))
        self.comboBox_7.setMaximumSize(QtCore.QSize(41, 30))
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_7)
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setMinimumSize(QtCore.QSize(41, 30))
        self.comboBox_8.setMaximumSize(QtCore.QSize(41, 30))
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_8)
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 30))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(280, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(30, 30))
        self.label_11.setMaximumSize(QtCore.QSize(30, 30))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_6.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_3.addWidget(self.checkBox_6)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(30, 30))
        self.label_12.setMaximumSize(QtCore.QSize(30, 30))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_5.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_4.addWidget(self.checkBox_5)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(30, 30))
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_4.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_5.addWidget(self.checkBox_4)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(30, 30))
        self.label_14.setMaximumSize(QtCore.QSize(30, 30))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_3.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_6.addWidget(self.checkBox_3)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(30, 30))
        self.label_15.setMaximumSize(QtCore.QSize(30, 30))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_2.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(30, 30))
        self.label_16.setMaximumSize(QtCore.QSize(30, 30))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.checkBox_1 = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        self.checkBox_1.setMinimumSize(QtCore.QSize(16, 30))
        self.checkBox_1.setMaximumSize(QtCore.QSize(16, 30))
        self.checkBox_1.setText("")
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout_8.addWidget(self.checkBox_1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(160, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(160, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(160, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(160, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(538, 350))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(5800, 4000))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_9.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "六爻排盘"))
        Form.setToolTip(_translate("Form", "六爻排盘程序"))
        self.label_2.setText(_translate("Form", "公历"))
        self.comboBox.setItemText(0, _translate("Form", "2001"))
        self.comboBox.setItemText(1, _translate("Form", "2002"))
        self.comboBox.setItemText(2, _translate("Form", "2003"))
        self.comboBox.setItemText(3, _translate("Form", "2004"))
        self.comboBox.setItemText(4, _translate("Form", "2005"))
        self.comboBox.setItemText(5, _translate("Form", "2006"))
        self.comboBox.setItemText(6, _translate("Form", "2007"))
        self.comboBox.setItemText(7, _translate("Form", "2008"))
        self.comboBox.setItemText(8, _translate("Form", "2009"))
        self.comboBox.setItemText(9, _translate("Form", "2010"))
        self.comboBox.setItemText(10, _translate("Form", "2011"))
        self.comboBox.setItemText(11, _translate("Form", "2012"))
        self.comboBox.setItemText(12, _translate("Form", "2013"))
        self.comboBox.setItemText(13, _translate("Form", "2014"))
        self.comboBox.setItemText(14, _translate("Form", "2015"))
        self.comboBox.setItemText(15, _translate("Form", "2016"))
        self.comboBox.setItemText(16, _translate("Form", "2017"))
        self.comboBox.setItemText(17, _translate("Form", "2018"))
        self.comboBox.setItemText(18, _translate("Form", "2019"))
        self.comboBox.setItemText(19, _translate("Form", "2020"))
        self.comboBox.setItemText(20, _translate("Form", "2022"))
        self.comboBox.setItemText(21, _translate("Form", "2023"))
        self.comboBox.setItemText(22, _translate("Form", "2024"))
        self.comboBox.setItemText(23, _translate("Form", "2025"))
        self.comboBox.setItemText(24, _translate("Form", "2026"))
        self.comboBox.setItemText(25, _translate("Form", "2027"))
        self.comboBox.setItemText(26, _translate("Form", "2028"))
        self.comboBox.setItemText(27, _translate("Form", "2029"))
        self.comboBox.setItemText(28, _translate("Form", "2030"))
        self.comboBox.setItemText(29, _translate("Form", "2031"))
        self.comboBox.setItemText(30, _translate("Form", "2032"))
        self.comboBox.setItemText(31, _translate("Form", "2033"))
        self.comboBox.setItemText(32, _translate("Form", "2034"))
        self.comboBox.setItemText(33, _translate("Form", "2035"))
        self.comboBox.setItemText(34, _translate("Form", "2036"))
        self.comboBox.setItemText(35, _translate("Form", "2037"))
        self.comboBox.setItemText(36, _translate("Form", "2038"))
        self.comboBox.setItemText(37, _translate("Form", "2039"))
        self.comboBox.setItemText(38, _translate("Form", "2040"))
        self.label_3.setText(_translate("Form", "年"))
        self.comboBox_2.setItemText(0, _translate("Form", "1"))
        self.comboBox_2.setItemText(1, _translate("Form", "2"))
        self.comboBox_2.setItemText(2, _translate("Form", "3"))
        self.comboBox_2.setItemText(3, _translate("Form", "4"))
        self.comboBox_2.setItemText(4, _translate("Form", "5"))
        self.comboBox_2.setItemText(5, _translate("Form", "6"))
        self.comboBox_2.setItemText(6, _translate("Form", "7"))
        self.comboBox_2.setItemText(7, _translate("Form", "8"))
        self.comboBox_2.setItemText(8, _translate("Form", "9"))
        self.comboBox_2.setItemText(9, _translate("Form", "10"))
        self.comboBox_2.setItemText(10, _translate("Form", "11"))
        self.comboBox_2.setItemText(11, _translate("Form", "12"))
        self.label_4.setText(_translate("Form", "月"))
        self.comboBox_3.setItemText(0, _translate("Form", "1"))
        self.comboBox_3.setItemText(1, _translate("Form", "2"))
        self.comboBox_3.setItemText(2, _translate("Form", "3"))
        self.comboBox_3.setItemText(3, _translate("Form", "4"))
        self.comboBox_3.setItemText(4, _translate("Form", "5"))
        self.comboBox_3.setItemText(5, _translate("Form", "6"))
        self.comboBox_3.setItemText(6, _translate("Form", "7"))
        self.comboBox_3.setItemText(7, _translate("Form", "8"))
        self.comboBox_3.setItemText(8, _translate("Form", "9"))
        self.comboBox_3.setItemText(9, _translate("Form", "10"))
        self.comboBox_3.setItemText(10, _translate("Form", "11"))
        self.comboBox_3.setItemText(11, _translate("Form", "12"))
        self.comboBox_3.setItemText(12, _translate("Form", "13"))
        self.comboBox_3.setItemText(13, _translate("Form", "14"))
        self.comboBox_3.setItemText(14, _translate("Form", "15"))
        self.comboBox_3.setItemText(15, _translate("Form", "16"))
        self.comboBox_3.setItemText(16, _translate("Form", "17"))
        self.comboBox_3.setItemText(17, _translate("Form", "18"))
        self.comboBox_3.setItemText(18, _translate("Form", "19"))
        self.comboBox_3.setItemText(19, _translate("Form", "20"))
        self.comboBox_3.setItemText(20, _translate("Form", "21"))
        self.comboBox_3.setItemText(21, _translate("Form", "22"))
        self.comboBox_3.setItemText(22, _translate("Form", "23"))
        self.comboBox_3.setItemText(23, _translate("Form", "24"))
        self.comboBox_3.setItemText(24, _translate("Form", "25"))
        self.comboBox_3.setItemText(25, _translate("Form", "26"))
        self.comboBox_3.setItemText(26, _translate("Form", "27"))
        self.comboBox_3.setItemText(27, _translate("Form", "28"))
        self.comboBox_3.setItemText(28, _translate("Form", "29"))
        self.comboBox_3.setItemText(29, _translate("Form", "30"))
        self.comboBox_3.setItemText(30, _translate("Form", "31"))
        self.label_5.setText(_translate("Form", "日"))
        self.comboBox_4.setItemText(0, _translate("Form", "0"))
        self.comboBox_4.setItemText(1, _translate("Form", "1"))
        self.comboBox_4.setItemText(2, _translate("Form", "2"))
        self.comboBox_4.setItemText(3, _translate("Form", "3"))
        self.comboBox_4.setItemText(4, _translate("Form", "4"))
        self.comboBox_4.setItemText(5, _translate("Form", "5"))
        self.comboBox_4.setItemText(6, _translate("Form", "6"))
        self.comboBox_4.setItemText(7, _translate("Form", "7"))
        self.comboBox_4.setItemText(8, _translate("Form", "8"))
        self.comboBox_4.setItemText(9, _translate("Form", "9"))
        self.comboBox_4.setItemText(10, _translate("Form", "10"))
        self.comboBox_4.setItemText(11, _translate("Form", "11"))
        self.comboBox_4.setItemText(12, _translate("Form", "12"))
        self.comboBox_4.setItemText(13, _translate("Form", "13"))
        self.comboBox_4.setItemText(14, _translate("Form", "14"))
        self.comboBox_4.setItemText(15, _translate("Form", "15"))
        self.comboBox_4.setItemText(16, _translate("Form", "16"))
        self.comboBox_4.setItemText(17, _translate("Form", "17"))
        self.comboBox_4.setItemText(18, _translate("Form", "18"))
        self.comboBox_4.setItemText(19, _translate("Form", "19"))
        self.comboBox_4.setItemText(20, _translate("Form", "20"))
        self.comboBox_4.setItemText(21, _translate("Form", "21"))
        self.comboBox_4.setItemText(22, _translate("Form", "22"))
        self.comboBox_4.setItemText(23, _translate("Form", "23"))
        self.label_6.setText(_translate("Form", "点"))
        self.comboBox_5.setItemText(0, _translate("Form", "0"))
        self.comboBox_5.setItemText(1, _translate("Form", "1"))
        self.comboBox_5.setItemText(2, _translate("Form", "2"))
        self.comboBox_5.setItemText(3, _translate("Form", "3"))
        self.comboBox_5.setItemText(4, _translate("Form", "4"))
        self.comboBox_5.setItemText(5, _translate("Form", "5"))
        self.comboBox_5.setItemText(6, _translate("Form", "6"))
        self.comboBox_5.setItemText(7, _translate("Form", "7"))
        self.comboBox_5.setItemText(8, _translate("Form", "8"))
        self.comboBox_5.setItemText(9, _translate("Form", "9"))
        self.comboBox_5.setItemText(10, _translate("Form", "10"))
        self.comboBox_5.setItemText(11, _translate("Form", "11"))
        self.comboBox_5.setItemText(12, _translate("Form", "12"))
        self.comboBox_5.setItemText(13, _translate("Form", "13"))
        self.comboBox_5.setItemText(14, _translate("Form", "14"))
        self.comboBox_5.setItemText(15, _translate("Form", "15"))
        self.comboBox_5.setItemText(16, _translate("Form", "16"))
        self.comboBox_5.setItemText(17, _translate("Form", "17"))
        self.comboBox_5.setItemText(18, _translate("Form", "18"))
        self.comboBox_5.setItemText(19, _translate("Form", "19"))
        self.comboBox_5.setItemText(20, _translate("Form", "20"))
        self.comboBox_5.setItemText(21, _translate("Form", "21"))
        self.comboBox_5.setItemText(22, _translate("Form", "22"))
        self.comboBox_5.setItemText(23, _translate("Form", "23"))
        self.comboBox_5.setItemText(24, _translate("Form", "24"))
        self.comboBox_5.setItemText(25, _translate("Form", "25"))
        self.comboBox_5.setItemText(26, _translate("Form", "26"))
        self.comboBox_5.setItemText(27, _translate("Form", "27"))
        self.comboBox_5.setItemText(28, _translate("Form", "28"))
        self.comboBox_5.setItemText(29, _translate("Form", "29"))
        self.comboBox_5.setItemText(30, _translate("Form", "30"))
        self.comboBox_5.setItemText(31, _translate("Form", "31"))
        self.comboBox_5.setItemText(32, _translate("Form", "32"))
        self.comboBox_5.setItemText(33, _translate("Form", "33"))
        self.comboBox_5.setItemText(34, _translate("Form", "34"))
        self.comboBox_5.setItemText(35, _translate("Form", "35"))
        self.comboBox_5.setItemText(36, _translate("Form", "36"))
        self.comboBox_5.setItemText(37, _translate("Form", "37"))
        self.comboBox_5.setItemText(38, _translate("Form", "38"))
        self.comboBox_5.setItemText(39, _translate("Form", "39"))
        self.comboBox_5.setItemText(40, _translate("Form", "40"))
        self.comboBox_5.setItemText(41, _translate("Form", "41"))
        self.comboBox_5.setItemText(42, _translate("Form", "42"))
        self.comboBox_5.setItemText(43, _translate("Form", "43"))
        self.comboBox_5.setItemText(44, _translate("Form", "44"))
        self.comboBox_5.setItemText(45, _translate("Form", "45"))
        self.comboBox_5.setItemText(46, _translate("Form", "46"))
        self.comboBox_5.setItemText(47, _translate("Form", "47"))
        self.comboBox_5.setItemText(48, _translate("Form", "48"))
        self.comboBox_5.setItemText(49, _translate("Form", "49"))
        self.comboBox_5.setItemText(50, _translate("Form", "50"))
        self.comboBox_5.setItemText(51, _translate("Form", "51"))
        self.comboBox_5.setItemText(52, _translate("Form", "52"))
        self.comboBox_5.setItemText(53, _translate("Form", "53"))
        self.comboBox_5.setItemText(54, _translate("Form", "54"))
        self.comboBox_5.setItemText(55, _translate("Form", "55"))
        self.comboBox_5.setItemText(56, _translate("Form", "56"))
        self.comboBox_5.setItemText(57, _translate("Form", "57"))
        self.comboBox_5.setItemText(58, _translate("Form", "58"))
        self.comboBox_5.setItemText(59, _translate("Form", "59"))
        self.label_9.setText(_translate("Form", "分"))
        self.pushButton_10.setText(_translate("Form", "联系作者"))
        self.label_10.setText(_translate("Form", "农历"))
        self.comboBox_6.setItemText(0, _translate("Form", "子"))
        self.comboBox_6.setItemText(1, _translate("Form", "丑"))
        self.comboBox_6.setItemText(2, _translate("Form", "寅"))
        self.comboBox_6.setItemText(3, _translate("Form", "卯"))
        self.comboBox_6.setItemText(4, _translate("Form", "辰"))
        self.comboBox_6.setItemText(5, _translate("Form", "巳"))
        self.comboBox_6.setItemText(6, _translate("Form", "午"))
        self.comboBox_6.setItemText(7, _translate("Form", "未"))
        self.comboBox_6.setItemText(8, _translate("Form", "申"))
        self.comboBox_6.setItemText(9, _translate("Form", "酉"))
        self.comboBox_6.setItemText(10, _translate("Form", "戌"))
        self.comboBox_6.setItemText(11, _translate("Form", "亥"))
        self.label_7.setText(_translate("Form", "月"))
        self.comboBox_7.setItemText(0, _translate("Form", "甲"))
        self.comboBox_7.setItemText(1, _translate("Form", "乙"))
        self.comboBox_7.setItemText(2, _translate("Form", "丙"))
        self.comboBox_7.setItemText(3, _translate("Form", "丁"))
        self.comboBox_7.setItemText(4, _translate("Form", "戊"))
        self.comboBox_7.setItemText(5, _translate("Form", "己"))
        self.comboBox_7.setItemText(6, _translate("Form", "庚"))
        self.comboBox_7.setItemText(7, _translate("Form", "辛"))
        self.comboBox_7.setItemText(8, _translate("Form", "壬"))
        self.comboBox_7.setItemText(9, _translate("Form", "癸"))
        self.comboBox_8.setItemText(0, _translate("Form", "子"))
        self.comboBox_8.setItemText(1, _translate("Form", "丑"))
        self.comboBox_8.setItemText(2, _translate("Form", "寅"))
        self.comboBox_8.setItemText(3, _translate("Form", "卯"))
        self.comboBox_8.setItemText(4, _translate("Form", "辰"))
        self.comboBox_8.setItemText(5, _translate("Form", "巳"))
        self.comboBox_8.setItemText(6, _translate("Form", "午"))
        self.comboBox_8.setItemText(7, _translate("Form", "未"))
        self.comboBox_8.setItemText(8, _translate("Form", "申"))
        self.comboBox_8.setItemText(9, _translate("Form", "酉"))
        self.comboBox_8.setItemText(10, _translate("Form", "戌"))
        self.comboBox_8.setItemText(11, _translate("Form", "亥"))
        self.label_8.setText(_translate("Form", "日"))
        self.label.setText(_translate("Form", "占事："))
        self.label_11.setText(_translate("Form", "上爻"))
        self.pushButton_6.setText(_translate("Form", "■■■■■■"))
        self.label_12.setText(_translate("Form", "五爻"))
        self.pushButton_5.setText(_translate("Form", "■■■■■■"))
        self.label_13.setText(_translate("Form", "四爻"))
        self.pushButton_4.setText(_translate("Form", "■■■■■■"))
        self.label_14.setText(_translate("Form", "三爻"))
        self.pushButton_3.setText(_translate("Form", "■■■■■■"))
        self.label_15.setText(_translate("Form", "二爻"))
        self.pushButton_2.setText(_translate("Form", "■■■■■■"))
        self.label_16.setText(_translate("Form", "初爻"))
        self.pushButton.setText(_translate("Form", "■■■■■■"))
        self.pushButton_7.setText(_translate("Form", "排  盘"))
        self.pushButton_9.setText(_translate("Form", "复  制"))
        self.pushButton_8.setText(_translate("Form", "重  填"))

import imgr_rc
